### ISSUE TITLE
Seems like files missing !!!

### ISSUE THREAD

**Issue by GokulSamraj** [mariusbegby/cadence-discord-bot#427]
It seems like some bot files are missing which throws error in both dependency and and run time errors

kindly add those missing files and update the `package.json` versions

**Comment by mariusbegby** [comment]
@GokulSamraj What errors? Please provide more details.

**Comment by mariusbegby** [comment]
If you cannot provide more details, I will close this. You can use prebuilt Docker images here if you struggle with setting up your own environment correctly: https://hub.docker.com/r/mariusbegby/cadence/tags

Also, next time, please show some more respect, remember it is an open source project where people contribute their time for free. If you aren't satisfied with this bot then use another one, or fix the issues yourself (if you have the skill, n00b).

              It seems to be a cool idea but is this developer even sees the issues and working for the fixes?

_Originally posted by @GokulSamraj in https://github.com/mariusbegby/cadence-discord-bot/issues/337#issuecomment-2085620202_

**Comment by GokulSamraj** [comment]
LMAO chill dude
you are the one who didnt reply to that user who requested a feature
within 20 min you closed the issue and calling me a noob 😂

heres the issue i face 
![image](https://github.com/mariusbegby/cadence-discord-bot/assets/73090987/7e0419a6-2cd7-4208-97f1-5040bfb72653)

![image](https://github.com/mariusbegby/cadence-discord-bot/assets/73090987/e9ec0a0a-889a-4272-947e-19360732a5f1)


i was replicating the issue i faced before few hours

**Comment by mariusbegby** [comment]
@GokulSamraj what version of Node.js are you running?

Is this updated code from `main` branch, if not, which commit?

I need more details to reproduce. It is working fine here:

![image](https://github.com/mariusbegby/cadence-discord-bot/assets/25694918/a67a6e80-431e-4179-a5f0-6534d5348ce8)

**Comment by GokulSamraj** [comment]
![image](https://github.com/mariusbegby/cadence-discord-bot/assets/73090987/1ff0e91b-7e1a-485b-840a-e72cfbf78908)


main branch
windows 10
using node version manager (i used this thing in ubuntu previously and now using on windows)

your bot is perfectly fine for me , previously i used in replit and recently on ubuntu self host 
every time it worked fine ,except this new version . i recently switched to windows where all the problem started for me .

**Comment by mariusbegby** [comment]
I haven't tested Node.js v22 yet on Cadence.

Cadence is built to work on latest LTS version, which is currently v20. If you switch to Node.js v20 I am sure it will work again for you. There shouldn't be any issues in terms of Windows vs Linux, I use both myself (Windows on local development, Linux in production).

Node.js v22 will become LTS in October, and so I will test it properly and make required changes before that. I am still quite busy but from the summer I will finally start having free time again to work on hobby projects. So stay tuned for more updates. 

Let me know if you face issues with v20, but for now this seems like an issue only on your machine (unsupported version) ,so I will keep this closed.

**Comment by GokulSamraj** [comment]
thanks , version 20 fixed the issue
but few hours back it throwed a lot of error even in `npm i` 
i lost hope that i can use a music bot anymore
tbh your bot is way more stable after installation

![image](https://github.com/mariusbegby/cadence-discord-bot/assets/73090987/83796508-d805-41ab-8ec0-6ad0b7b017ce)

**Comment by mariusbegby** [comment]
Good to hear it works now.

On `main` branch there's a few dependencies having "vulnerability" warnings due to depending on vulnerable version of undici, however these are not actually something to worry about.

**Comment by GokulSamraj** [comment]
sadly after a system restart this error happend
this is what i faced previously

![image](https://github.com/mariusbegby/cadence-discord-bot/assets/73090987/65626c26-5e2c-4deb-82e0-eb7a7c642dec)

**Comment by pryzmian** [comment]
`Unexpected token '}'`

**Comment by mariusbegby** [comment]
`config` npm package is used to load the configuration from `/config/` folder.

It seems one of the config files are not formatted properly, hence `Unexpected token '}'` error as @pryzmian  mentioned.

The config file uses normal object structure. If you are unable to fix it, please provide all files inside `/config/` folder. ChatGPT might unironically help you find the issue also if you send it the error and file contents.

I can reproduce the error by intentionally putting invalid syntax in the config file:
![image](https://github.com/mariusbegby/cadence-discord-bot/assets/25694918/d109325f-d45b-4b53-a5b8-b6497d9d915e)

```
> cadence-discord-bot@5.7.0 start
> node .

E:\cadence-discord-bot\node_modules\config\lib\config.js:855
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: 'E:\cadence-discord-bot\config\default.js': SyntaxError: Unexpected token '{'
    at util.parseFile (E:\cadence-discord-bot\node_modules\config\lib\config.js:855:11)
    at E:\cadence-discord-bot\node_modules\config\lib\config.js:651:28
    at Array.forEach (<anonymous>)
    at util.loadFileConfigs (E:\cadence-discord-bot\node_modules\config\lib\config.js:650:16)
    at new Config (E:\cadence-discord-bot\node_modules\config\lib\config.js:116:27)
    at Object.<anonymous> (E:\cadence-discord-bot\node_modules\config\lib\config.js:1515:33)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)

Node.js v20.12.0
```

If you are using VS Code, I recommend using this extension and opening the config file. You should see errors in syntax highlighted very clearly (see screenshot)
![image](https://github.com/mariusbegby/cadence-discord-bot/assets/25694918/c3c44997-32bd-4fb9-b012-0aa763ee2ff2)

**Comment by GokulSamraj** [comment]
@mariusbegby the isssue is fixed, thanks ✌

**Comment by GokulSamraj** [comment]
nvm , a new issue started
for both your own bot and the one i folked
![image](https://github.com/mariusbegby/cadence-discord-bot/assets/73090987/cd428b39-82d6-49b4-811f-c9f6e8b4ce93)

**Comment by mariusbegby** [comment]
@GokulSamraj that is an extrordinary issue that happened due to one of our dependencies, youtube-ext. The issue was external and affected all bots running with `youtube-ext` as backend for getting tracks from youtube (and spotify).

Please join the support server for information like this.

**Comment by mariusbegby** [comment]
**Temporary fix:**
- Use `npm install @distube/ytdl-core --save`, `npm remove youtube-ext --save` (changes dependency for youtube extraction)
- Remove ipRotationConfig from `createPlayer.ts` completely, like so:

```ts
const player: Player = new Player(client, {
    useLegacyFFmpeg: false,
    skipFFmpeg: false,
    ytdlOptions: {
        quality: 'highestaudio',
        highWaterMark: 1 << 25,
        // no ipRotationConfig here
        requestOptions: {
            headers: {
                cookie: process.env.YT_COOKIE || ''
            }
        }
    }
});
```

Then `npm run build` and restart.

**Comment by GokulSamraj** [comment]
this temporary fix worked as charm @mariusbegby 
also joined your discord channel
waiting for a permanent fix

**Comment by mariusbegby** [comment]
Nice. Stay tuned for updates in the Discord server. The fix needs to be issued by package maintainer for the dependency package `youtube-ext`, unfortunately out of my control. I will update on Discord when fix is available (commit to bump version number of dependency)

**Comment by xtcorp** [comment]
Faced the same problem. Re-inviting bot with discord's new "installation" tab somehow fixed it
![2024-05-06_04-48](https://github.com/mariusbegby/cadence-discord-bot/assets/23431506/b8b18844-647b-4cc5-acc7-c8b757305a0b)
