### ISSUE TITLE
Request to change library to mediaplex due to discord-voip error

### ISSUE THREAD

**Issue by CodeName393** [mariusbegby/cadence-discord-bot#474]
Existing discord-voip causes an error and appears to fail Opus conversion.
I checked the normal operation when I changed it to mediaplex.

`[11:28:38.203] ERROR: player.events.on('error'): Player queue encountered error event
    err: {
      "type": "AbortError",
      "message": "The operation was aborted: This operation was aborted",
      "stack":
          AbortError: The operation was aborted
              at EventTarget.abortListener (node:events:1007:14)
              at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
              at EventTarget.dispatchEvent (node:internal/event_target:755:26)
              at abortSignal (node:internal/abort_controller:370:10)
              at AbortController.abort (node:internal/abort_controller:392:5)
              at Timeout.<anonymous> (D:\Program\Development\Test\node_modules\discord-voip\dist\index.js:2529:39)
              at listOnTimeout (node:internal/timers:573:17)
              at process.processTimers (node:internal/timers:514:7)
          caused by: AbortError: This operation was aborted
              at new DOMException (node:internal/per_context/domexception:53:5)
              at AbortController.abort (node:internal/abort_controller:391:18)
              at Timeout.<anonymous> (D:\Program\Development\Test\node_modules\discord-voip\dist\index.js:2529:39)
              at listOnTimeout (node:internal/timers:573:17)
              at process.processTimers (node:internal/timers:514:7)
      "code": "ABORT_ERR",
      "name": "AbortError"
    }`

**Comment by mariusbegby** [comment]
`discord-voip` and `mediaplex` have different uses.

The error seems to be from a timeout or sudden loss of internet connection. Using the two dependencies works fine for me. What particular problem are you experiencing? Without being able to reproduce, there is little i can do.
